{
 "title": "Mysticeti",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TPS (per node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(latency_s_count[1m])" }
   ]
  },
  {
   "title": "Latency(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg(transaction_certified_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Certificate p50"
    },
    {
     "expr": "avg(transaction_certified_latency{v=\"p90\"}) / 1000",
     "legendFormat": "Certificate p90"
    },
    {
     "expr": "avg(transaction_committed_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Tx Commit p50"
    },
    {
     "expr": "avg(transaction_committed_latency{v=\"p90\"}) / 1000",
     "legendFormat": "Tx Commit p90"
    },
    {
     "expr": "avg(certificate_committed_latency{v=\"p50\"}) / 1000",
     "legendFormat": "Cert commit p50"
    },
    {
     "expr": "avg(certificate_committed_latency{v=\"p90\"}) / 1000",
     "legendFormat": "Cert commit p90"
    }
   ]
  },
  {
   "title": "Total Submitted Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(submitted_transactions[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(submitted_transactions[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Core thread utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(core_lock_util[1m]) / 1000000 * 100"
    }
   ]
  },
  {
   "title": "Avg connection latency (by peer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(connection_latency{v=\"p50\"} / 1000) by (peer)"
    }
   ]
  },
  {
   "title": "Proposed block size p50(Kbytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "proposed_block_size_bytes{v=\"p50\"} / 1024"
    }
   ]
  },
  {
   "title": "Core queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "core_lock_enqueued - core_lock_dequeued"
    }
   ]
  },
  {
   "title": "Committed Leaders (view of Node 0)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "committed_leaders_total", "legendFormat": "Node {{authority}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / 1024 / 1024 /1024"
    }
   ]
  },
  {
   "title": "FPC Block Processor Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "rate(fpc_block_util[1m]) / 1000000 * 100"
    }
   ]
  },
  {
   "title": "FPC Block Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fpc_block_enqueued - fpc_block_dequeued"
    }
   ]
  },
  {
   "title": "FPC Commit Processor Utilization %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "rate(fpc_commit_util[1m]) / 1000000 * 100"
    }
   ]
  },
  {
   "title": "FPC Commit Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "fpc_commit_enqueued - fpc_commit_dequeued"
    }
   ]
  },
  {
   "title": "Network receive (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"ens5\"}[1m]) / 1024 / 1024 * 8"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Network Traffic (MB/s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo\"}[1m]) / 1024 / 1024",
     "legendFormat": "Inbound ({{instance}})"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo\"}[1m]) / 1024 / 1024",
     "legendFormat": "Outbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Latency Breakdown (Stacked)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(latency_breakdown_1_queue_sum[1m]) / rate(latency_breakdown_1_queue_count[1m])",
     "legendFormat": "Queue"
    },
    {
     "expr": "rate(latency_breakdown_2_verify_sum[1m]) / rate(latency_breakdown_2_verify_count[1m])",
     "legendFormat": "Verify"
    },
    {
     "expr": "(rate(latency_breakdown_pre_consensus_sum[1m]) / rate(latency_breakdown_pre_consensus_count[1m])) - ((rate(latency_breakdown_1_queue_sum[1m]) / rate(latency_breakdown_1_queue_count[1m])) + (rate(latency_breakdown_2_verify_sum[1m]) / rate(latency_breakdown_2_verify_count[1m])))",
     "legendFormat": "Batching"
    },
    {
     "expr": "rate(latency_breakdown_4_cert_sum[1m]) / rate(latency_breakdown_4_cert_count[1m])",
     "legendFormat": "Certification"
    },
    {
     "expr": "(sum(rate(latency_breakdown_5_commit_sum[1m])) / sum(rate(latency_breakdown_5_commit_count[1m]))) - (rate(latency_breakdown_4_cert_sum[1m]) / rate(latency_breakdown_4_cert_count[1m]))",
     "legendFormat": "Commit"
    }
   ]
  }
 ]
}